create unique index exercises_predefined_name_unique_idx
  on public.exercises (name)
  where owner_id is null;


insert into public.exercises (
  owner_id,
  name
)
values
  -- General strength and bodybuilding
  (null, 'Barbell Back Squat'),
  (null, 'Goblet Squat'),
  (null, 'Hack Squat'),
  (null, 'Leg Press'),
  (null, 'Bulgarian Split Squat'),
  (null, 'Walking Lunge'),
  (null, 'Reverse Lunge'),
  (null, 'Leg Extension'),
  (null, 'Seated Leg Curl'),
  (null, 'Lying Leg Curl'),
  (null, 'Romanian Deadlift'),
  (null, 'Barbell Hip Thrust'),
  (null, 'Glute Bridge'),
  (null, 'Standing Calf Raise'),
  (null, 'Seated Calf Raise'),
  (null, 'Barbell Bench Press'),
  (null, 'Incline Barbell Bench Press'),
  (null, 'Dumbbell Bench Press'),
  (null, 'Incline Dumbbell Bench Press'),
  (null, 'Machine Chest Press'),
  (null, 'Cable Chest Fly'),
  (null, 'Pec Deck'),
  (null, 'Push-Up'),
  (null, 'Barbell Overhead Press'),
  (null, 'Dumbbell Shoulder Press'),
  (null, 'Arnold Press'),
  (null, 'Dumbbell Lateral Raise'),
  (null, 'Cable Lateral Raise'),
  (null, 'Rear Delt Fly'),
  (null, 'Pull-Up'),
  (null, 'Chin-Up'),
  (null, 'Lat Pulldown'),
  (null, 'Bent-Over Barbell Row'),
  (null, 'One-Arm Dumbbell Row'),
  (null, 'Chest-Supported Row'),
  (null, 'Seated Cable Row'),
  (null, 'Face Pull'),
  (null, 'Barbell Shrug'),
  (null, 'Barbell Curl'),
  (null, 'Dumbbell Curl'),
  (null, 'Hammer Curl'),
  (null, 'Preacher Curl'),
  (null, 'Cable Curl'),
  (null, 'Triceps Pushdown'),
  (null, 'Overhead Triceps Extension'),
  (null, 'Skull Crusher'),
  (null, 'Close-Grip Bench Press'),
  (null, 'Plank'),
  (null, 'Side Plank'),
  (null, 'Hanging Knee Raise'),
  (null, 'Hanging Leg Raise'),
  (null, 'Cable Crunch'),
  (null, 'Ab Wheel Rollout'),
  (null, 'Russian Twist'),
  (null, 'Back Extension'),
  (null, 'Farmer’s Carry'),
  (null, 'Sled Push'),
  (null, 'Sled Pull'),

  -- Powerlifting and common variants/accessories
  (null, 'Competition Back Squat'),
  (null, 'Pause Squat'),
  (null, 'Tempo Squat'),
  (null, 'Box Squat'),
  (null, 'Competition Bench Press'),
  (null, 'Paused Bench Press'),
  (null, 'Spoto Press'),
  (null, 'Floor Press'),
  (null, 'Conventional Deadlift'),
  (null, 'Sumo Deadlift'),
  (null, 'Deficit Deadlift'),
  (null, 'Rack Pull'),
  (null, 'Good Morning'),

  -- Olympic weightlifting
  (null, 'Snatch'),
  (null, 'Clean and Jerk'),
  (null, 'Clean'),
  (null, 'Power Clean'),
  (null, 'Hang Clean'),
  (null, 'Hang Power Clean'),
  (null, 'Muscle Clean'),
  (null, 'Clean Pull'),
  (null, 'Clean High Pull'),
  (null, 'Jerk'),
  (null, 'Split Jerk'),
  (null, 'Push Jerk'),
  (null, 'Power Snatch'),
  (null, 'Hang Snatch'),
  (null, 'Hang Power Snatch'),
  (null, 'Muscle Snatch'),
  (null, 'Snatch Pull'),
  (null, 'Snatch High Pull'),
  (null, 'Snatch Balance'),
  (null, 'Overhead Squat'),
  (null, 'Front Squat'),
  (null, 'Push Press'),
  (null, 'Sots Press'),

  -- CrossFit and functional fitness
  (null, 'Air Squat'),
  (null, 'Front-Rack Lunge'),
  (null, 'Wall-Ball Shot'),
  (null, 'Thruster'),
  (null, 'Medicine-Ball Clean'),
  (null, 'Sumo Deadlift High Pull'),
  (null, 'Kettlebell Swing'),
  (null, 'Kettlebell Snatch'),
  (null, 'Dumbbell Clean'),
  (null, 'Dumbbell Power Snatch'),
  (null, 'Dumbbell Thruster'),
  (null, 'Turkish Get-Up'),
  (null, 'Burpee'),
  (null, 'Bar-Facing Burpee'),
  (null, 'Burpee Box Jump-Over'),
  (null, 'Box Jump'),
  (null, 'Box Step-Up'),
  (null, 'Single-Under'),
  (null, 'Double-Under'),
  (null, 'Toes-to-Bar'),
  (null, 'Knees-to-Elbows'),
  (null, 'Strict Pull-Up'),
  (null, 'Kipping Pull-Up'),
  (null, 'Chest-to-Bar Pull-Up'),
  (null, 'Bar Muscle-Up'),
  (null, 'Ring Muscle-Up'),
  (null, 'Ring Dip'),
  (null, 'Handstand Push-Up'),
  (null, 'Handstand Walk'),
  (null, 'Wall Walk'),
  (null, 'Rope Climb'),
  (null, 'Legless Rope Climb'),
  (null, 'GHD Sit-Up'),
  (null, 'Row Erg'),
  (null, 'Ski Erg'),
  (null, 'Bike Erg')
on conflict (name)
  where owner_id is null
  do nothing;